# Physics plugin: constrain Create robot to 2D plane
# For Mac .app: WEBOTS_HOME_PATH must point to Contents (has Resources)
# WEBOTS_HOME must point to .app root (for Contents/include)

null :=
space := $(null) $(null)
WEBOTS_HOME ?= /Applications/Webots.app
WEBOTS_HOME_PATH ?= $(WEBOTS_HOME)/Contents
include $(WEBOTS_HOME_PATH)/Resources/Makefile.include
